# Generated by Django 4.1.5 on 2023-01-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="amount",
            field=models.PositiveIntegerField(
                default=100, help_text="The number of products available in stock"
            ),
        ),
        migrations.AlterField(
            model_name="productrating",
            name="count",
            field=models.PositiveIntegerField(
                help_text="The number of ratings of the product"
            ),
        ),
    ]
