# Generated by Django 4.1.5 on 2023-01-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_product_amount_alter_productrating_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productrating",
            name="count",
            field=models.PositiveIntegerField(
                default=0, help_text="The number of ratings of the product"
            ),
        ),
        migrations.AlterField(
            model_name="productrating",
            name="rate",
            field=models.FloatField(default=0, help_text="The product rating"),
        ),
    ]
