# Generated by Django 4.1.5 on 2023-01-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_productrating_count_alter_productrating_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="rating_count",
            field=models.PositiveIntegerField(
                default=0, help_text="The number of ratings of the product"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.FloatField(default=0, help_text="The product rating"),
        ),
        migrations.DeleteModel(
            name="ProductRating",
        ),
    ]
